[default.probe]
# USB VID/PID of probe, optional
# usb_vid = "1337"
# usb_pid = "1337"

# Serial number of probe, optional
# serial = "001122334455"

# protocol to select, can be "JTAG" or "Swd", depending on what the probe supports
# protocol = "Swd"

# speed for the interface
# speed = 4000

[default.flashing]
# whether to halt the chip after flashing
halt_afterwards = false

# whether to restore a broken UICR after flashing
restore_unwritten_bytes = false

[default.reset]
# whether to enable the chip after flashing  
halt_afterwards = false

[default.general]
# The chip of the target
chip = "nRF52820_xxAA"

# A list of chips to try if chip (above) can't be found.
chip_descriptions = []

# The default log level to be used by the probe-rs tools.
log_level = "WARN"

# Use this flag to assert the nreset & ntrst pins during attaching the probe to the chip
connect_under_reset = false

[default.rtt]
# Whether or not to enable RTT logging
enabled = true

# A list of channel associations to be displayed.
channels = [
    # { up = 0, down = 0, name = "Terminal", up_mode = "NoBlockSkip", format = "Defmt" },
    { up = 0, down = 0, name = "Terminal", up_mode = "NoBlockSkip", format = "Defmt" },
]

# The timeout in ms for which to wait for the host to connect to the probe before continuing flashing.
timeout = 3000

# Whether or not to show the location of the log messages
show_location = true