[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF52820_xxAA with your chip's target
runner = "probe-rs run --chip nRF52820_xxAA --log-format=oneline"
# runner = ["probe-rs", "run", "--chip", "$CHIP", "--log-format=oneline"]

rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C",
  "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"

