[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF52820_xxAA with your chip's target
runner = "probe-rs run --chip nRF52820_xxAA --log-format=oneline"
# runner = ["probe-rs", "run", "--chip", "$CHIP", "--log-format=oneline"]

rustflags = [
  # "-C",
  # "linker=flip-link",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=--nmagic",
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"


[alias]
test-all = """
test \
--test bonding_tests \
--test command_tests \
--test connection_tests \
--test end_to_end_tests \
--test event_tests \
--test gatt_tests \
--test integration_tests \
--test notification_tests \
--test protocol_tests \
--test spi_tests \
"""
